services:
  # User Service
  user-service:
    build:
      context: ./user-service/backend
    container_name: user-service
    environment:
      DB_HOST: user-database
      DB_USER: user_service_user
      DB_PASS: user_service_pass
      DB_NAME: user_service_db
    depends_on:
      - user-database
    networks:
      - library-net
    ports:
      - "5001:5001"

  user-database:
    image: mysql:latest
    container_name: user-database
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: user_service_db
      MYSQL_USER: user_service_user
      MYSQL_PASSWORD: user_service_pass
    networks:
      - library-net
    volumes:
      - ./user-service/database/scripts/db/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - ./database/user-db:/var/lib/mysql
    ports:
      - "3306:3306"

  # Catalog Service
  catalog-service:
    build:
      context: ./catalog-service/backend
    container_name: catalog-service
    environment:
      DB_HOST: catalog-database
      DB_USER: catalog_user
      DB_PASS: catalog_pass
      DB_NAME: catalog_db
    depends_on:
      - catalog-database
    networks:
      - library-net
    ports:
      - "5002:5000"

  catalog-database:
    image: mysql:latest
    container_name: catalog-database
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: catalog_db
      MYSQL_USER: catalog_user
      MYSQL_PASSWORD: catalog_pass
    networks:
      - library-net
    volumes:
      - ./catalog-service/database/scripts/db/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - ./database/catalog-db:/var/lib/mysql

    ports:
      - "3307:3306"

  # Order Service
  order-service:
    build:
      context: ./order-service/backend
    container_name: order-service
    environment:
      DB_HOST: order-database
      DB_NAME: order_service_db
      DB_USER: order_service_user
      DB_PASS: order_service_pass
    depends_on:
      - order-database
    networks:
      - library-net
    ports:
      - "5003:80"

  order-database:
    image: mysql:latest
    container_name: order-database
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: order_service_db
      MYSQL_USER: order_service_user
      MYSQL_PASSWORD: order_service_pass
    networks:
      - library-net
    volumes:
      - ./order-service/database/scripts/db/dump.sql:/docker-entrypoint-initdb.d/dump.sql
      - ./database/order-db:/var/lib/mysql
    ports:
      - "3308:3306"

  # Frontend
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    depends_on:
      - user-service
      - catalog-service
      - order-service
    networks:
      - library-net
    ports:
      - "3000:80"

networks:
 library-net:
    driver: bridge




