version: '3.8'

services:
  order-service:
    build:
      context: ./backend
    container_name: order-service
    environment:
      DB_HOST: database
      DB_NAME: order_service_db
      DB_USER: order_service_user
      DB_PASS: order_service_pass
    depends_on:
      - database
    networks:
      - order-net
    ports:
      - "8080:80"

  database:
    build:
      context: ./database
    container_name: order-database
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: order_service_db
      MYSQL_USER: order_service_user
      MYSQL_PASSWORD: order_service_pass
    networks:
      - order-net
    ports:
      - "3306:3306"

networks:
  order-net:
    driver: bridge
